export const countries = {
  "AFG": "Afghanistan",
  "ALA": "Åland Islands",
  "ALB": "Albania",
  "AND": "Andorra",
  "AGO": "Angola",
  "AIA": "Anguilla",
  "ATA": "Antarctica",
  "ATG": "Antigua and Barbuda",
  "ARG": "Argentina",
  "ARM": "Armenia",
  "ABW": "Aruba",
  "AUS": "Australia",
  "AUT": "Austria",
  "AZE": "Azerbaijan",
  "BDI": "Burundi",
  "BEL": "Belgium",
  "BEN": "Benin",
  "BHS": "Bahamas",
  "BHU": "Bhutan",
  "BIH": "Bosnia and Herzegovina",
  "BLR": "Belarus",
  "BOL": "Bolivia",
  "BLZ": "Belize",
  "BMU": "Bermuda",
  "BNE": "Brunei Darussalam",
  "BOG": "Bulgaria",
  "BRA": "Brazil",
  "BRN": "Brunei",
  "BTN": "Bhutan",
  "BVT": "Bouvet Island",
  "BWA": "Botswana",
  "CAF": "Central African Republic",
  "CAN": "Canada",
  "CCK": "Cocos (Keeling) Islands",
  "CHE": "Switzerland",
  "CHL": "Chile",
  "CHN": "China",
  "CIV": "Ivory Coast",
  "CMR": "Cameroon",
  "COD": "Congo, Democratic Republic of the",
  "COG": "Congo",
  "COL": "Colombia",
  "COM": "Comoros",
  "CPV": "Cape Verde",
  "CRI": "Costa Rica",
  "CUB": "Cuba",
  "CUW": "Curaçao",
  "CXR": "Christmas Island",
  "CYP": "Cyprus",
  "CZE": "Czech Republic",
  "DEU": "Germany",
  "DJI": "Djibouti",
  "DMA": "Dominica",
  "DNK": "Denmark",
  "DOM": "Dominican Republic",
  "DZA": "Algeria",
  "ECU": "Ecuador",
  "EGY": "Egypt",
  "ERI": "Eritrea",
  "ESH": "Western Sahara",
  "ESP": "Spain",
  "EST": "Estonia",
  "ETH": "Ethiopia",
  "FIN": "Finland",
  "FJI": "Fiji",
  "FLK": "Falkland Islands (Malvinas)",
  "FRA": "France",
  "FRO": "Faroe Islands",
  "FSM": "Micronesia, Federated States of",
  "GAB": "Gabon",
  "GBR": "United Kingdom",
  "GEO": "Georgia",
  "GGY": "Guernsey",
  "GHA": "Ghana",
  "GIB": "Gibraltar",
  "GIN": "Guinea",
  "GLP": "Guadeloupe",
  "GMB": "Gambia",
  "GNB": "Guinea-Bissau",
  "GNQ": "Equatorial Guinea",
  "GRC": "Greece",
  "GRD": "Grenada",
  "GTM": "Guatemala",
  "GUF": "French Guiana",
  "GUM": "Guam",
  "GUY": "Guyana",
  "HKG": "Hong Kong",
  "HMD": "Heard Island and McDonald Islands",
  "HND": "Honduras",
  "HRV": "Croatia",
  "HTI": "Haiti",
  "HUN": "Hungary",
  "IDN": "Indonesia",
  "IMN": "Isle of Man",
  "IND": "India",
  "IOT": "British Indian Ocean Territory",
  "IRQ": "Iraq",
  "IRL": "Ireland",
}
